title: Active Learning with Neural Processes for Epidemiology Modeling
author: "Amogh Patankar"
description:  Improving multi-fidelity epidemiology modeling with neural processes and active learning. 
github:
  repository_url: https://github.com/apatankar22/hier-neural-proc/tree/main
theme: jekyll-theme-cayman
